### ISSUE TITLE
NumberFormatException when dialog is open.

### ISSUE THREAD

**Issue by geheur** [WolffTech/coal-bag-addon#2]
Getting this error when this interface is open:

java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.coalbagplugin.CoalBagPlugin.onGameTick(CoalBagPlugin.java:121)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:66)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:219)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
	at client.gd(client.java:48480)
	at client.ak(client.java)
	at aa.hx(aa.java:362)
	at aa.run(aa.java:316)
	at java.base/java.lang.Thread.run(Thread.java:832)

![image](https://user-images.githubusercontent.com/41499327/124500488-ba82a100-dd74-11eb-9af5-113c8d73e514.png)

**Comment by Blackberry0Pie** [comment]
Happens with Temple Trekking reward dialogue too

**Comment by WolffTech** [comment]
Fixed in 1.2 Release
